GET http://localhost:9098/currency_exchange_war/currencies/
Accept: application/json

###
GET http://localhost:9098/currency_exchange_war/currency/usd

Accept: application/json

###
POST http://localhost:9098/currency_exchange_war/currencies
Content-Type: application/x-www-form-urlencoded

name=Japanese Yen&code=JPY&sign=¥

###
GET http://localhost:9098/currency_exchange_war/exchangeRates
Accept: application/json

###
// TODO fix 404
POST http://localhost:9098/currency_exchange_war/exchangeRates
Content-Type: application/json

{
  "baseCurrencyCode": "USD",
  "targetCurrencyCode": "JPY",
  "rate": 110.0
}


###
GET http://localhost:9098/currency_exchange_war/exchangeRate/USDEUR
Accept: application/json

###
// TODO fix 400
PATCH http://localhost:9098/currency_exchange_war/exchangeRate/USDEUR
Content-Type: application/json

{
  "rate": 1.11
}


